---
apiVersion: v1
kind: Namespace
metadata:
  name: prodns

---
apiVersion: v1
kind: Pod
metadata:
  name: myweb
  namespace: prodns
spec:
  containers:
    - name: myweb-container
      image: nginx:1.14
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 200m
          memory: 100Mi
        limits:
          cpu: 1
          memory: 200Mi
      env:
        - name: DB
          value: mydb






