apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      name: rs-nginx-pod
      labels:
        app: webui
    spec:
      containers:
        - name: rs-nginx-container
          image: nginx:1.14
          ports:
            - containerPort: 80
